-- NirmaanSetu MVP schema. UUID values are generated by the application layer.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE app_user (
    id UUID PRIMARY KEY,
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_user_account_status CHECK (account_status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE app_role (
    id UUID PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT chk_app_role_code CHECK (code IN ('CLIENT', 'WORKER', 'CONTRACTOR', 'ADMIN'))
);

CREATE TABLE user_role (
    user_id UUID NOT NULL REFERENCES app_user(id),
    role_id UUID NOT NULL REFERENCES app_role(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE skill (
    id UUID PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_skill_code CHECK (code = UPPER(code))
);

CREATE TABLE worker_profile (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES app_user(id),
    display_name VARCHAR(120) NOT NULL,
    experience_years SMALLINT,
    location VARCHAR(255) NOT NULL,
    availability_status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    daily_rate NUMERIC(12, 2),
    profile_description TEXT,
    is_travel_willing BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_worker_profile_display_name CHECK (BTRIM(display_name) <> ''),
    CONSTRAINT chk_worker_profile_experience CHECK (experience_years IS NULL OR experience_years >= 0),
    CONSTRAINT chk_worker_profile_daily_rate CHECK (daily_rate IS NULL OR daily_rate >= 0),
    CONSTRAINT chk_worker_profile_availability CHECK (availability_status IN ('AVAILABLE', 'LIMITED', 'UNAVAILABLE'))
);

CREATE TABLE worker_skill (
    worker_profile_id UUID NOT NULL REFERENCES worker_profile(id),
    skill_id UUID NOT NULL REFERENCES skill(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (worker_profile_id, skill_id)
);

CREATE TABLE contractor_profile (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES app_user(id),
    display_name VARCHAR(160) NOT NULL,
    description TEXT,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_contractor_profile_display_name CHECK (BTRIM(display_name) <> '')
);

CREATE TABLE client_profile (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES app_user(id),
    client_type VARCHAR(30) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_client_profile_type CHECK (client_type IN ('HOMEOWNER', 'BUILDER', 'BUSINESS', 'OTHER')),
    CONSTRAINT chk_client_profile_display_name CHECK (BTRIM(display_name) <> '')
);

CREATE TABLE team (
    id UUID PRIMARY KEY,
    manager_user_id UUID NOT NULL REFERENCES app_user(id),
    name VARCHAR(160) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_team_name CHECK (BTRIM(name) <> ''),
    CONSTRAINT chk_team_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE team_member (
    team_id UUID NOT NULL REFERENCES team(id),
    worker_profile_id UUID NOT NULL REFERENCES worker_profile(id),
    starts_on DATE NOT NULL,
    ends_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (team_id, worker_profile_id, starts_on),
    CONSTRAINT chk_team_member_dates CHECK (ends_on IS NULL OR ends_on >= starts_on)
);

CREATE TABLE contractor_worker_association (
    contractor_profile_id UUID NOT NULL REFERENCES contractor_profile(id),
    worker_profile_id UUID NOT NULL REFERENCES worker_profile(id),
    starts_on DATE NOT NULL,
    ends_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (contractor_profile_id, worker_profile_id, starts_on),
    CONSTRAINT chk_contractor_worker_association_dates CHECK (ends_on IS NULL OR ends_on >= starts_on)
);

CREATE TABLE project (
    id UUID PRIMARY KEY,
    client_profile_id UUID NOT NULL REFERENCES client_profile(id),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    location VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    start_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_project_title CHECK (BTRIM(title) <> ''),
    CONSTRAINT chk_project_status CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE workforce_requirement (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES project(id),
    location VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    duration_days INTEGER NOT NULL,
    worker_type VARCHAR(30) NOT NULL,
    skill_id UUID NOT NULL REFERENCES skill(id),
    quantity INTEGER NOT NULL,
    daily_rate NUMERIC(12, 2),
    budget_amount NUMERIC(14, 2),
    currency_code CHAR(3) NOT NULL DEFAULT 'INR',
    accommodation_available BOOLEAN NOT NULL DEFAULT FALSE,
    food_available BOOLEAN NOT NULL DEFAULT FALSE,
    additional_notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_requirement_duration CHECK (duration_days > 0),
    CONSTRAINT chk_requirement_worker_type CHECK (worker_type IN ('SKILLED_WORKER', 'LABOUR')),
    CONSTRAINT chk_requirement_quantity CHECK (quantity > 0),
    CONSTRAINT chk_requirement_daily_rate CHECK (daily_rate IS NULL OR daily_rate >= 0),
    CONSTRAINT chk_requirement_budget_amount CHECK (budget_amount IS NULL OR budget_amount >= 0),
    CONSTRAINT chk_requirement_currency_code CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT chk_requirement_status CHECK (status IN ('DRAFT', 'OPEN', 'FULFILLED', 'CANCELLED'))
);

CREATE TABLE booking (
    id UUID PRIMARY KEY,
    requirement_id UUID NOT NULL REFERENCES workforce_requirement(id),
    provider_type VARCHAR(20) NOT NULL,
    provider_worker_profile_id UUID REFERENCES worker_profile(id),
    provider_team_id UUID REFERENCES team(id),
    provider_contractor_profile_id UUID REFERENCES contractor_profile(id),
    quantity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_booking_provider CHECK (
        (provider_type = 'WORKER' AND provider_worker_profile_id IS NOT NULL AND provider_team_id IS NULL AND provider_contractor_profile_id IS NULL)
        OR (provider_type = 'TEAM' AND provider_worker_profile_id IS NULL AND provider_team_id IS NOT NULL AND provider_contractor_profile_id IS NULL)
        OR (provider_type = 'CONTRACTOR' AND provider_worker_profile_id IS NULL AND provider_team_id IS NULL AND provider_contractor_profile_id IS NOT NULL)
    ),
    CONSTRAINT chk_booking_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT chk_booking_quantity CHECK (
        quantity > 0
        AND (provider_type <> 'WORKER' OR quantity = 1)
    ),
    CONSTRAINT chk_booking_response CHECK (
        (status = 'PENDING' AND responded_at IS NULL)
        OR (status IN ('ACCEPTED', 'REJECTED') AND responded_at IS NOT NULL)
    )
);

CREATE TABLE verification (
    id UUID PRIMARY KEY,
    subject_type VARCHAR(30) NOT NULL,
    subject_user_id UUID REFERENCES app_user(id),
    subject_worker_profile_id UUID REFERENCES worker_profile(id),
    subject_contractor_profile_id UUID REFERENCES contractor_profile(id),
    subject_client_profile_id UUID REFERENCES client_profile(id),
    verification_type VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by_user_id UUID REFERENCES app_user(id),
    reviewed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_verification_subject CHECK (
        (subject_type = 'USER' AND subject_user_id IS NOT NULL AND subject_worker_profile_id IS NULL AND subject_contractor_profile_id IS NULL AND subject_client_profile_id IS NULL)
        OR (subject_type = 'WORKER' AND subject_user_id IS NULL AND subject_worker_profile_id IS NOT NULL AND subject_contractor_profile_id IS NULL AND subject_client_profile_id IS NULL)
        OR (subject_type = 'CONTRACTOR' AND subject_user_id IS NULL AND subject_worker_profile_id IS NULL AND subject_contractor_profile_id IS NOT NULL AND subject_client_profile_id IS NULL)
        OR (subject_type = 'CLIENT' AND subject_user_id IS NULL AND subject_worker_profile_id IS NULL AND subject_contractor_profile_id IS NULL AND subject_client_profile_id IS NOT NULL)
    ),
    CONSTRAINT chk_verification_type CHECK (verification_type = 'MANUAL'),
    CONSTRAINT chk_verification_status CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT chk_verification_review CHECK (
        (status = 'PENDING' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL)
        OR (status IN ('VERIFIED', 'REJECTED') AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

CREATE INDEX idx_worker_profile_available_location
    ON worker_profile (location)
    WHERE availability_status = 'AVAILABLE';
CREATE INDEX idx_worker_skill_skill_worker ON worker_skill (skill_id, worker_profile_id);
CREATE INDEX idx_contractor_profile_location ON contractor_profile (location);
CREATE INDEX idx_team_member_worker_dates ON team_member (worker_profile_id, starts_on, ends_on);
CREATE INDEX idx_contractor_worker_association_worker_dates
    ON contractor_worker_association (worker_profile_id, starts_on, ends_on);
CREATE INDEX idx_project_client_status ON project (client_profile_id, status);
CREATE INDEX idx_requirement_open_location_start
    ON workforce_requirement (location, start_date)
    WHERE status = 'OPEN';
CREATE INDEX idx_booking_requirement ON booking (requirement_id);
CREATE INDEX idx_booking_worker_provider
    ON booking (provider_worker_profile_id)
    WHERE provider_worker_profile_id IS NOT NULL;
CREATE INDEX idx_booking_team_provider
    ON booking (provider_team_id)
    WHERE provider_team_id IS NOT NULL;
CREATE INDEX idx_booking_contractor_provider
    ON booking (provider_contractor_profile_id)
    WHERE provider_contractor_profile_id IS NOT NULL;

CREATE TRIGGER trg_app_user_updated_at BEFORE UPDATE ON app_user FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_worker_profile_updated_at BEFORE UPDATE ON worker_profile FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_contractor_profile_updated_at BEFORE UPDATE ON contractor_profile FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_client_profile_updated_at BEFORE UPDATE ON client_profile FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_team_updated_at BEFORE UPDATE ON team FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_project_updated_at BEFORE UPDATE ON project FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_workforce_requirement_updated_at BEFORE UPDATE ON workforce_requirement FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_booking_updated_at BEFORE UPDATE ON booking FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_verification_updated_at BEFORE UPDATE ON verification FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO app_role (id, code) VALUES
    ('00000000-0000-0000-0000-000000000001', 'CLIENT'),
    ('00000000-0000-0000-0000-000000000002', 'WORKER'),
    ('00000000-0000-0000-0000-000000000003', 'CONTRACTOR'),
    ('00000000-0000-0000-0000-000000000004', 'ADMIN');

INSERT INTO skill (id, code, name) VALUES
    ('10000000-0000-0000-0000-000000000001', 'RAJ_MISTRI', 'Raj Mistri'),
    ('10000000-0000-0000-0000-000000000002', 'MASON', 'Mason'),
    ('10000000-0000-0000-0000-000000000003', 'BRICKWORK', 'Brickwork'),
    ('10000000-0000-0000-0000-000000000004', 'PLASTERING', 'Plastering'),
    ('10000000-0000-0000-0000-000000000005', 'RCC', 'RCC'),
    ('10000000-0000-0000-0000-000000000006', 'CARPENTER', 'Carpenter'),
    ('10000000-0000-0000-0000-000000000007', 'ELECTRICIAN', 'Electrician'),
    ('10000000-0000-0000-0000-000000000008', 'PLUMBER', 'Plumber'),
    ('10000000-0000-0000-0000-000000000009', 'PAINTER', 'Painter'),
    ('10000000-0000-0000-0000-000000000010', 'TILE_WORKER', 'Tile Worker'),
    ('10000000-0000-0000-0000-000000000011', 'SHUTTERING_WORKER', 'Shuttering Worker'),
    ('10000000-0000-0000-0000-000000000012', 'BAR_BENDER', 'Bar Bender'),
    ('10000000-0000-0000-0000-000000000013', 'LABOUR', 'Labour');
